name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DATASOURCE_PASSWORD: 'HM5cWm1XStxOiZLtlvA9esjylwmLrGrS'
      DATASOURCE_URL: 'jdbc:postgresql://dpg-cl19sbk8s0fs739l6i5g-a.frankfurt-postgres.render.com:5432/trainingsplandb'
      DATASOURCE_USERNAME: 'server'

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Backend Tests
        run: ./gradlew test

